### ISSUE TITLE
Error: Interface "PrintOptions" has already been declared

### ISSUE THREAD

**Issue by zeke** [electron/typescript-definitions#56]
Here's what I'm seeing on electron/electron master when running `npm run create-typescript-definitions`:

```
[ { name: 'deviceName',
    type: 'string',
    collection: false,
    description: undefined,
    required: true },
  { name: 'printBackground',
    type: 'boolean',
    collection: false,
    description: undefined,
    required: true },
  { name: 'silent',
    type: 'boolean',
    collection: false,
    description: undefined,
    required: true } ] '\n' [ { name: 'printBackground',
    type: 'boolean',
    collection: false,
    description: undefined,
    required: true },
  { name: 'silent',
    type: 'boolean',
    collection: false,
    description: undefined,
    required: true } ]
Error: Interface "PrintOptions" has already been declared
    at Object.createParamInterface (/Users/z/git/electron/electron/node_modules/electron-typescript-definitions/lib/dynamic-param-interfaces.js:55:11)
    at map (/Users/z/git/electron/electron/node_modules/electron-typescript-definitions/lib/utils.js:146:39)
    at Array.map (native)
    at Object.genMethodString (/Users/z/git/electron/electron/node_modules/electron-typescript-definitions/lib/utils.js:137:57)
    at addMethod (/Users/z/git/electron/electron/node_modules/electron-typescript-definitions/lib/module-declaration.js:132:31)
    at module.methods.sort.forEach.m (/Users/z/git/electron/electron/node_modules/electron-typescript-definitions/lib/module-declaration.js:153:21)
    at Array.forEach (native)
    at Object.generateModuleDeclaration (/Users/z/git/electron/electron/node_modules/electron-typescript-definitions/lib/module-declaration.js:153:8)
    at API.sort.forEach (/Users/z/git/electron/electron/node_modules/electron-typescript-definitions/index.js:58:23)
    at Array.forEach (native)
```

@poiru said in Slack:

> It's due to the mismatch between `contents.print` and `<webview>.print`

I'm guessing we could solve this by using a more distinct name for each, like `webContentsPrintOptions` and `webviewTagPrintOptions`. Does that sound right?

cc @MarshallOfSound

**Comment by kevinsawicki** [comment]
This error shouldn't happen anymore on master since https://github.com/electron/electron/commit/dcb22d34b5bd72bf4fb8ecbc236189203c9d3360

The signatures for these two methods should be the *exact* same so they probably should use the same options object

**Comment by zeke** [comment]
See also https://github.com/electron/electron/pull/9603

**Comment by MarshallOfSound** [comment]
@zeke @kevinsawicki Has this issue been fixed then?

**Comment by zeke** [comment]
Fixed in the sense that nothing is currently on fire. But still needs attention. See  https://github.com/electron/electron/pull/9603

**Comment by MarshallOfSound** [comment]
Shweet, I had a fix for this lying around somewhere from when I was testing typescript stuff for the new Notification API and had to fix this to make it work 😄

**Comment by MarshallOfSound** [comment]
Fixed in `master`
